[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["cd backend/server", "npm ci", "npx prisma generate"]

[phases.build] 
cmds = ["cd backend/server", "npm run build"]

[start]
cmd = "cd backend/server && npm run start:prod"

[variables]
NODE_ENV = "production"